INFO 2022-04-09 23:48:12,041 autoreload 637 38581 140734910164416 Watching for file changes with StatReloader
INFO 2022-04-09 23:48:42,936 autoreload 251 38581 140734910164416 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-09 23:48:43,531 autoreload 637 38687 140734872128960 Watching for file changes with StatReloader
INFO 2022-04-09 23:48:58,398 autoreload 637 38747 140734925548992 Watching for file changes with StatReloader
INFO 2022-04-09 23:49:09,607 basehttp 161 38747 123145475121152 "GET /home/home HTTP/1.1" 301 0
ERROR 2022-04-09 23:49:09,631 exceptions 7 38747 123145475121152 view是<luffyapi.apps.home.views.TestView object at 0x10a35b978>，错误是'age'
INFO 2022-04-09 23:49:09,678 basehttp 161 38747 123145475121152 "GET /home/home/ HTTP/1.1" 200 5248
INFO 2022-04-09 23:49:09,759 basehttp 161 38747 123145480376320 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2022-04-09 23:49:09,762 basehttp 161 38747 123145485631488 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2022-04-09 23:49:09,768 basehttp 161 38747 123145501396992 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2022-04-09 23:49:09,769 basehttp 161 38747 123145480376320 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2022-04-09 23:49:09,771 basehttp 161 38747 123145490886656 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2022-04-09 23:49:09,777 basehttp 161 38747 123145485631488 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2022-04-09 23:49:09,781 basehttp 161 38747 123145501396992 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2022-04-09 23:49:09,783 basehttp 161 38747 123145496141824 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
INFO 2022-04-09 23:49:09,784 basehttp 161 38747 123145480376320 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2022-04-09 23:49:09,797 basehttp 161 38747 123145475121152 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2022-04-09 23:49:09,852 basehttp 161 38747 123145475121152 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2022-04-09 23:51:42,766 autoreload 251 38747 140734925548992 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-09 23:51:43,389 autoreload 637 39257 140734928235968 Watching for file changes with StatReloader
ERROR 2022-04-09 23:51:47,579 exceptions 7 39257 123145313161216 view是<luffyapi.apps.home.views.TestView object at 0x10a3d4278>，错误是'age'
INFO 2022-04-09 23:51:47,622 basehttp 161 39257 123145313161216 "GET /home/home/ HTTP/1.1" 200 5248
INFO 2022-04-09 23:52:43,128 autoreload 251 39257 140734928235968 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-09 23:52:43,850 autoreload 637 39445 140734855318976 Watching for file changes with StatReloader
ERROR 2022-04-09 23:59:58,871 exceptions 7 39445 123145379471360 view是TestView，错误是'age'
INFO 2022-04-09 23:59:58,902 basehttp 161 39445 123145379471360 "GET /home/home/ HTTP/1.1" 200 5248
INFO 2022-04-09 23:59:58,936 basehttp 161 39445 123145379471360 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,941 basehttp 161 39445 123145379471360 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,949 basehttp 161 39445 123145384726528 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,960 basehttp 161 39445 123145395236864 "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,973 basehttp 161 39445 123145395236864 "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,978 basehttp 161 39445 123145400492032 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,980 basehttp 161 39445 123145389981696 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,981 basehttp 161 39445 123145379471360 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,986 basehttp 161 39445 123145405747200 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2022-04-09 23:59:58,994 basehttp 161 39445 123145384726528 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2022-04-09 23:59:59,012 basehttp 161 39445 123145384726528 "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
INFO 2022-04-10 12:32:33,020 autoreload 637 52391 140734830525888 Watching for file changes with StatReloader
INFO 2022-04-10 12:34:37,412 autoreload 637 52778 140734819663296 Watching for file changes with StatReloader
ERROR 2022-04-10 13:13:16,622 exceptions 7 52778 123145391374336 view是TestView，错误是'age'
INFO 2022-04-10 13:13:16,674 basehttp 161 52778 123145391374336 "GET /home/home/ HTTP/1.1" 200 5248
INFO 2022-04-10 13:13:16,748 basehttp 161 52778 123145401884672 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,755 basehttp 161 52778 123145391374336 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,756 basehttp 161 52778 123145396629504 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,761 basehttp 161 52778 123145391374336 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,770 basehttp 161 52778 123145412395008 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,774 basehttp 161 52778 123145407139840 "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,775 basehttp 161 52778 123145401884672 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,777 basehttp 161 52778 123145417650176 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,779 basehttp 161 52778 123145396629504 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,779 basehttp 161 52778 123145391374336 "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2022-04-10 13:13:16,794 basehttp 161 52778 123145396629504 "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
INFO 2022-04-10 13:18:18,513 autoreload 251 52778 140734819663296 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 13:18:20,297 autoreload 637 60681 140734806531520 Watching for file changes with StatReloader
ERROR 2022-04-10 13:27:19,839 exceptions 7 60681 123145412300800 view是TestView，错误是'age'
INFO 2022-04-10 13:27:19,896 basehttp 161 60681 123145412300800 "GET /home/home/ HTTP/1.1" 200 5248
WARNING 2022-04-10 13:27:20,175 basehttp 161 60681 123145412300800 "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1879
INFO 2022-04-10 13:28:39,528 autoreload 637 62594 140734758190528 Watching for file changes with StatReloader
INFO 2022-04-10 13:28:49,457 autoreload 637 62636 140734950378944 Watching for file changes with StatReloader
ERROR 2022-04-10 13:28:56,589 exceptions 7 62636 123145414180864 view是TestView，错误是'age'
INFO 2022-04-10 13:28:56,622 basehttp 161 62636 123145414180864 "GET /home/home/ HTTP/1.1" 200 5248
WARNING 2022-04-10 13:28:56,756 basehttp 161 62636 123145414180864 "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1879
ERROR 2022-04-10 13:36:29,080 exceptions 7 62636 123145414180864 view是TestView，错误是'age'
INFO 2022-04-10 13:36:29,084 basehttp 161 62636 123145414180864 "GET /home/home/ HTTP/1.1" 200 48
INFO 2022-04-10 14:14:44,280 autoreload 251 62636 140734950378944 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 14:14:45,657 autoreload 637 70933 140734935707072 Watching for file changes with StatReloader
INFO 2022-04-10 14:15:35,753 autoreload 251 70933 140734935707072 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 14:15:36,525 autoreload 637 71099 140734990917056 Watching for file changes with StatReloader
INFO 2022-04-10 14:15:45,247 autoreload 251 71099 140734990917056 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 14:15:45,930 autoreload 637 71133 140734772391360 Watching for file changes with StatReloader
ERROR 2022-04-10 14:27:22,805 exceptions 7 71133 123145565769728 view是TestView，错误是'age'
INFO 2022-04-10 14:27:22,807 basehttp 161 71133 123145565769728 "GET /home/home/ HTTP/1.1" 200 48
ERROR 2022-04-10 14:29:37,096 exceptions 7 71133 123145571024896 view是TestView，错误是'age'
INFO 2022-04-10 14:29:37,175 basehttp 161 71133 123145571024896 "GET /home/home/ HTTP/1.1" 200 5248
WARNING 2022-04-10 14:29:37,462 basehttp 161 71133 123145571024896 "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1879
INFO 2022-04-10 14:29:54,844 autoreload 251 71133 140734772391360 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 14:29:56,795 autoreload 637 73719 140734892486080 Watching for file changes with StatReloader
ERROR 2022-04-10 14:30:01,488 exceptions 7 73719 123145343246336 view是TestView，错误是'age'
INFO 2022-04-10 14:30:01,548 basehttp 161 73719 123145343246336 "GET /home/home/ HTTP/1.1" 200 5248
WARNING 2022-04-10 14:30:01,732 basehttp 161 73719 123145343246336 "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1879
ERROR 2022-04-10 14:30:17,784 exceptions 7 73719 123145343246336 view是TestView，错误是'age'
INFO 2022-04-10 14:30:17,787 basehttp 161 73719 123145343246336 "GET /home/home/ HTTP/1.1" 200 48
ERROR 2022-04-10 14:30:46,436 exceptions 7 73719 123145343246336 view是TestView，错误是'age'
INFO 2022-04-10 14:30:46,438 basehttp 161 73719 123145343246336 "GET /home/home/ HTTP/1.1" 200 48
INFO 2022-04-10 14:33:23,452 autoreload 251 73719 140734892486080 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 14:33:25,342 autoreload 637 74378 140734818315712 Watching for file changes with StatReloader
ERROR 2022-04-10 14:33:30,596 exceptions 7 74378 123145507078144 view是TestView，错误是'age'
INFO 2022-04-10 14:33:30,599 basehttp 161 74378 123145507078144 "GET /home/home/ HTTP/1.1" 200 48
ERROR 2022-04-10 14:33:53,961 exceptions 7 74378 123145507078144 view是TestView，错误是'age'
INFO 2022-04-10 14:33:53,963 basehttp 161 74378 123145507078144 "GET /home/home/ HTTP/1.1" 200 48
INFO 2022-04-10 14:35:45,304 autoreload 251 74378 140734818315712 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 14:35:47,203 autoreload 637 74833 140734759886272 Watching for file changes with StatReloader
INFO 2022-04-10 14:52:09,810 autoreload 637 77818 140734815911360 Watching for file changes with StatReloader
ERROR 2022-04-10 14:52:17,676 exceptions 7 77818 123145469546496 view是TestView，错误是'age'
INFO 2022-04-10 14:52:17,679 basehttp 161 77818 123145469546496 "GET /home/home/ HTTP/1.1" 200 48
ERROR 2022-04-10 17:22:15,386 exceptions 7 77818 123145469546496 view是TestView，错误是'age'
INFO 2022-04-10 17:22:15,387 basehttp 161 77818 123145469546496 "GET /home/home/ HTTP/1.1" 200 48
INFO 2022-04-10 17:31:31,581 autoreload 251 77818 140734815911360 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:31:33,941 autoreload 637 6403 140734992670144 Watching for file changes with StatReloader
INFO 2022-04-10 17:31:38,370 autoreload 251 6403 140734992670144 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:31:39,920 autoreload 637 6427 140734770257344 Watching for file changes with StatReloader
INFO 2022-04-10 17:31:41,195 autoreload 251 6427 140734770257344 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:31:41,798 autoreload 637 6438 140734967197120 Watching for file changes with StatReloader
INFO 2022-04-10 17:31:46,123 autoreload 251 6438 140734967197120 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:31:46,772 autoreload 637 6457 140734795898304 Watching for file changes with StatReloader
INFO 2022-04-10 17:31:59,344 autoreload 251 6457 140734795898304 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:00,278 autoreload 637 6498 140735000071616 Watching for file changes with StatReloader
INFO 2022-04-10 17:32:04,722 autoreload 251 6498 140735000071616 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:05,444 autoreload 637 6517 140734953500096 Watching for file changes with StatReloader
INFO 2022-04-10 17:32:12,896 autoreload 251 6517 140734953500096 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:13,967 autoreload 637 6556 140735006109120 Watching for file changes with StatReloader
INFO 2022-04-10 17:32:22,491 autoreload 251 6556 140735006109120 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:23,677 autoreload 637 6589 140734982892992 Watching for file changes with StatReloader
INFO 2022-04-10 17:32:36,440 autoreload 251 6589 140734982892992 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:37,488 autoreload 637 6642 140734767766976 Watching for file changes with StatReloader
INFO 2022-04-10 17:32:51,229 autoreload 251 6642 140734767766976 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:51,914 autoreload 637 6693 140734975118784 Watching for file changes with StatReloader
INFO 2022-04-10 17:32:58,364 autoreload 251 6693 140734975118784 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:32:59,415 autoreload 637 6725 140734941679040 Watching for file changes with StatReloader
INFO 2022-04-10 17:33:07,942 autoreload 251 6725 140734941679040 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:33:08,787 autoreload 637 6757 140734860742080 Watching for file changes with StatReloader
INFO 2022-04-10 17:33:15,212 autoreload 251 6757 140734860742080 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:33:16,178 autoreload 637 6787 140734982626752 Watching for file changes with StatReloader
INFO 2022-04-10 17:33:23,599 autoreload 251 6787 140734982626752 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:33:24,184 autoreload 637 6816 140734834343360 Watching for file changes with StatReloader
INFO 2022-04-10 17:33:45,055 autoreload 251 6816 140734834343360 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:33:45,916 autoreload 637 6892 140734850538944 Watching for file changes with StatReloader
INFO 2022-04-10 17:33:56,470 autoreload 251 6892 140734850538944 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:33:57,133 autoreload 637 6929 140734909820352 Watching for file changes with StatReloader
INFO 2022-04-10 17:34:39,750 autoreload 251 6929 140734909820352 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/urls.py changed, reloading.
INFO 2022-04-10 17:34:40,553 autoreload 637 7071 140734975966656 Watching for file changes with StatReloader
INFO 2022-04-10 17:34:47,556 basehttp 161 7071 123145336496128 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 17:35:51,724 autoreload 251 7071 140734975966656 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:35:52,859 autoreload 637 7359 140734995996096 Watching for file changes with StatReloader
INFO 2022-04-10 17:35:56,801 basehttp 161 7359 123145442463744 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 17:36:11,056 autoreload 251 7359 140734995996096 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 17:36:12,020 autoreload 637 7430 140734764191168 Watching for file changes with StatReloader
INFO 2022-04-10 17:36:15,981 basehttp 161 7430 123145352822784 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 17:58:56,377 basehttp 161 7430 123145352822784 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 18:00:29,325 basehttp 161 7430 123145352822784 "GET /home/home/ HTTP/1.1" 200 2
ERROR 2022-04-10 18:00:54,768 log 230 7430 123145352822784 Internal Server Error: /home/home
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/middleware/common.py", line 95, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/home/home/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2022-04-10 18:00:54,771 basehttp 161 7430 123145352822784 "POST /home/home HTTP/1.1" 500 64650
WARNING 2022-04-10 18:01:17,016 log 230 7430 123145352822784 Forbidden (CSRF cookie not set.): /home/home/
WARNING 2022-04-10 18:01:17,017 basehttp 161 7430 123145352822784 "POST /home/home/ HTTP/1.1" 403 2801
INFO 2022-04-10 18:02:39,124 autoreload 251 7430 140734764191168 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 18:02:41,196 autoreload 637 12185 140734754188736 Watching for file changes with StatReloader
INFO 2022-04-10 18:02:43,592 basehttp 161 12185 123145542856704 "POST /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 18:18:40,937 autoreload 251 12185 140734754188736 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 18:18:42,552 autoreload 637 15113 140734873042368 Watching for file changes with StatReloader
INFO 2022-04-10 18:20:39,634 autoreload 251 15113 140734873042368 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/home/views.py changed, reloading.
INFO 2022-04-10 18:20:40,943 autoreload 637 15478 140734789651904 Watching for file changes with StatReloader
INFO 2022-04-10 18:21:30,253 basehttp 161 15478 123145577062400 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 18:21:34,845 basehttp 161 15478 123145577062400 "POST /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 18:29:41,209 autoreload 251 15478 140734789651904 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 18:29:42,499 autoreload 637 17111 140734943407552 Watching for file changes with StatReloader
INFO 2022-04-10 18:31:35,229 autoreload 251 17111 140734943407552 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 18:31:35,831 autoreload 637 17518 140734808088000 Watching for file changes with StatReloader
INFO 2022-04-10 18:31:48,247 autoreload 251 17518 140734808088000 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 18:31:48,734 autoreload 637 17569 140734819823040 Watching for file changes with StatReloader
INFO 2022-04-10 18:32:00,099 autoreload 251 17569 140734819823040 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 18:32:01,077 autoreload 637 17607 140734871498176 Watching for file changes with StatReloader
INFO 2022-04-10 19:14:02,105 autoreload 251 17607 140734871498176 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:14:04,683 autoreload 637 25094 140734875913664 Watching for file changes with StatReloader
INFO 2022-04-10 19:14:25,994 autoreload 251 25094 140734875913664 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:14:26,707 autoreload 637 25173 140734970514880 Watching for file changes with StatReloader
INFO 2022-04-10 19:14:38,438 autoreload 251 25173 140734970514880 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:14:39,019 autoreload 637 25219 140734951968192 Watching for file changes with StatReloader
INFO 2022-04-10 19:14:44,715 autoreload 251 25219 140734951968192 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:14:45,395 autoreload 637 25253 140734748523968 Watching for file changes with StatReloader
INFO 2022-04-10 19:14:49,953 autoreload 251 25253 140734748523968 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:14:50,545 autoreload 637 25275 140734911278528 Watching for file changes with StatReloader
INFO 2022-04-10 19:15:03,574 autoreload 251 25275 140734911278528 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:15:04,428 autoreload 637 25320 140734870166976 Watching for file changes with StatReloader
INFO 2022-04-10 19:15:10,053 autoreload 251 25320 140734870166976 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:15:10,921 autoreload 637 25345 140734754397632 Watching for file changes with StatReloader
INFO 2022-04-10 19:19:53,908 autoreload 251 25345 140734754397632 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:19:56,054 autoreload 637 26217 140734928981440 Watching for file changes with StatReloader
INFO 2022-04-10 19:20:06,114 autoreload 251 26217 140734928981440 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:20:06,904 autoreload 637 26257 140734932016576 Watching for file changes with StatReloader
INFO 2022-04-10 19:20:22,022 autoreload 251 26257 140734932016576 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:20:23,247 autoreload 637 26311 140734877208000 Watching for file changes with StatReloader
INFO 2022-04-10 19:20:58,181 autoreload 251 26311 140734877208000 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:20:59,433 autoreload 637 26429 140734970019264 Watching for file changes with StatReloader
INFO 2022-04-10 19:21:24,041 autoreload 251 26429 140734970019264 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:21:25,276 autoreload 637 26510 140734976560576 Watching for file changes with StatReloader
INFO 2022-04-10 19:26:51,392 autoreload 251 26510 140734976560576 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:26:53,385 autoreload 637 27500 140734868192704 Watching for file changes with StatReloader
INFO 2022-04-10 19:29:09,065 autoreload 251 27500 140734868192704 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:29:11,317 autoreload 637 27930 140735003782592 Watching for file changes with StatReloader
INFO 2022-04-10 19:32:24,582 autoreload 251 27930 140735003782592 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 19:32:26,638 autoreload 637 28541 140734858214848 Watching for file changes with StatReloader
INFO 2022-04-10 19:32:35,607 basehttp 161 28541 123145409515520 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 19:32:45,681 basehttp 161 28541 123145409515520 "POST /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 19:32:48,829 basehttp 161 28541 123145414770688 "GET /home/home/ HTTP/1.1" 200 2
INFO 2022-04-10 20:20:27,836 autoreload 637 38490 140735003835840 Watching for file changes with StatReloader
INFO 2022-04-10 20:20:58,236 autoreload 637 38635 140734956633536 Watching for file changes with StatReloader
INFO 2022-04-10 20:23:39,073 autoreload 637 39145 140734889463232 Watching for file changes with StatReloader
INFO 2022-04-10 20:27:59,586 autoreload 251 39145 140734889463232 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:28:01,240 autoreload 637 39945 140734964542912 Watching for file changes with StatReloader
INFO 2022-04-10 20:29:14,742 autoreload 251 39945 140734964542912 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:29:16,408 autoreload 637 40195 140734940356032 Watching for file changes with StatReloader
INFO 2022-04-10 20:29:32,927 autoreload 251 40195 140734940356032 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:29:33,581 autoreload 637 40258 140734983089600 Watching for file changes with StatReloader
INFO 2022-04-10 20:31:10,673 autoreload 637 40559 140734954626496 Watching for file changes with StatReloader
INFO 2022-04-10 20:31:18,045 autoreload 251 40559 140734954626496 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:31:18,821 autoreload 637 40582 140734823501248 Watching for file changes with StatReloader
INFO 2022-04-10 20:31:30,257 autoreload 251 40582 140734823501248 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:31:31,967 autoreload 637 40628 140734738578880 Watching for file changes with StatReloader
INFO 2022-04-10 20:33:27,254 autoreload 251 40628 140734738578880 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 20:33:29,397 autoreload 637 41000 140734878580160 Watching for file changes with StatReloader
INFO 2022-04-10 20:33:45,918 autoreload 251 41000 140734878580160 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 20:33:46,639 autoreload 637 41061 140734768950720 Watching for file changes with StatReloader
INFO 2022-04-10 20:34:08,246 autoreload 251 41061 140734768950720 /Users/zhangjiangying/study/luffyapi/luffyapi/settings/dev.py changed, reloading.
INFO 2022-04-10 20:34:08,803 autoreload 637 41129 140734902754752 Watching for file changes with StatReloader
INFO 2022-04-10 20:35:24,263 autoreload 251 41129 140734902754752 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 20:35:25,933 autoreload 637 41364 140734788369856 Watching for file changes with StatReloader
INFO 2022-04-10 20:35:42,478 autoreload 251 41364 140734788369856 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 20:35:43,221 autoreload 637 41437 140734804336064 Watching for file changes with StatReloader
INFO 2022-04-10 20:36:51,570 autoreload 251 41437 140734804336064 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 20:36:53,225 autoreload 637 41653 140734766333376 Watching for file changes with StatReloader
INFO 2022-04-10 20:36:59,559 autoreload 251 41653 140734766333376 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 20:37:00,132 autoreload 637 41687 140734771129792 Watching for file changes with StatReloader
INFO 2022-04-10 20:37:24,744 autoreload 251 41687 140734771129792 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:37:25,301 autoreload 637 41758 140734879567296 Watching for file changes with StatReloader
INFO 2022-04-10 20:37:50,962 autoreload 251 41758 140734879567296 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:37:51,521 autoreload 637 41866 140734808542656 Watching for file changes with StatReloader
INFO 2022-04-10 20:38:05,947 autoreload 251 41866 140734808542656 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:38:06,507 autoreload 637 41916 140734862319040 Watching for file changes with StatReloader
INFO 2022-04-10 20:38:27,042 autoreload 251 41916 140734862319040 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/models.py changed, reloading.
INFO 2022-04-10 20:38:28,127 autoreload 637 41984 140734785048000 Watching for file changes with StatReloader
INFO 2022-04-10 20:40:00,921 autoreload 251 41984 140734785048000 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py changed, reloading.
INFO 2022-04-10 20:40:02,675 autoreload 637 42282 140734988062144 Watching for file changes with StatReloader
INFO 2022-04-10 20:40:37,582 autoreload 251 42282 140734988062144 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py changed, reloading.
INFO 2022-04-10 20:40:39,387 autoreload 637 42403 140734839332288 Watching for file changes with StatReloader
INFO 2022-04-10 20:41:01,998 autoreload 251 42403 140734839332288 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py changed, reloading.
INFO 2022-04-10 20:41:02,735 autoreload 637 42478 140734854340032 Watching for file changes with StatReloader
INFO 2022-04-10 20:41:24,390 autoreload 251 42478 140734854340032 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/dashboard.py changed, reloading.
INFO 2022-04-10 20:41:25,752 autoreload 637 42542 140734824775104 Watching for file changes with StatReloader
INFO 2022-04-10 20:41:53,493 autoreload 251 42542 140734824775104 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/dashboard.py changed, reloading.
INFO 2022-04-10 20:41:54,204 autoreload 637 42639 140734898933184 Watching for file changes with StatReloader
INFO 2022-04-10 20:45:58,841 autoreload 251 42639 140734898933184 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py changed, reloading.
INFO 2022-04-10 20:46:01,228 autoreload 637 43400 140735004679616 Watching for file changes with StatReloader
INFO 2022-04-10 20:46:07,567 autoreload 251 43400 140735004679616 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py changed, reloading.
INFO 2022-04-10 20:46:08,242 autoreload 637 43427 140734931140032 Watching for file changes with StatReloader
INFO 2022-04-10 20:49:12,064 autoreload 578 44203 140734800461248 Watching for file changes with StatReloader
INFO 2022-04-10 20:53:35,075 autoreload 578 45087 140735004155328 Watching for file changes with StatReloader
INFO 2022-04-10 20:53:59,597 autoreload 578 45176 140734782000576 Watching for file changes with StatReloader
INFO 2022-04-10 20:54:14,799 autoreload 578 45234 140734903287232 Watching for file changes with StatReloader
INFO 2022-04-10 20:54:52,231 autoreload 578 45360 140734918073792 Watching for file changes with StatReloader
INFO 2022-04-10 20:55:02,896 autoreload 578 45404 140734813703616 Watching for file changes with StatReloader
INFO 2022-04-10 20:55:27,055 autoreload 578 45482 140734910787008 Watching for file changes with StatReloader
INFO 2022-04-10 20:55:57,122 autoreload 578 45587 140734859566528 Watching for file changes with StatReloader
INFO 2022-04-10 20:57:44,878 autoreload 578 45986 140734774517184 Watching for file changes with StatReloader
INFO 2022-04-10 21:00:00,062 autoreload 578 46414 140734957551040 Watching for file changes with StatReloader
INFO 2022-04-10 21:01:47,231 autoreload 578 46752 140734844374464 Watching for file changes with StatReloader
INFO 2022-04-10 21:02:10,006 autoreload 578 46831 140734937365952 Watching for file changes with StatReloader
INFO 2022-04-10 21:02:22,738 autoreload 578 46874 140734743522752 Watching for file changes with StatReloader
INFO 2022-04-10 21:05:28,556 autoreload 578 47458 140734815698368 Watching for file changes with StatReloader
INFO 2022-04-10 21:05:50,204 autoreload 578 47539 140734952259008 Watching for file changes with StatReloader
INFO 2022-04-10 21:10:33,025 autoreload 203 47539 140734952259008 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/db/backends/mysql/operations.py changed, reloading.
INFO 2022-04-10 21:10:34,623 autoreload 578 48405 140734805081536 Watching for file changes with StatReloader
INFO 2022-04-10 21:11:25,406 autoreload 578 48572 140734848536000 Watching for file changes with StatReloader
WARNING 2022-04-10 21:12:23,484 log 228 48572 123145361702912 Not Found: /admin
WARNING 2022-04-10 21:12:23,484 basehttp 154 48572 123145361702912 "GET /admin HTTP/1.1" 404 2291
INFO 2022-04-10 21:12:28,379 basehttp 154 48572 123145361702912 "GET /xadmin HTTP/1.1" 301 0
ERROR 2022-04-10 21:12:28,508 log 228 48572 123145361702912 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    return login(request, **defaults)
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:12:28,514 basehttp 154 48572 123145361702912 "GET /xadmin/ HTTP/1.1" 500 89825
INFO 2022-04-10 21:18:54,667 autoreload 578 50048 140734748356032 Watching for file changes with StatReloader
ERROR 2022-04-10 21:18:59,961 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    return login(request, **defaults)
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:18:59,963 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 89960
ERROR 2022-04-10 21:19:02,265 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    return login(request, **defaults)
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:19:02,266 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 89960
ERROR 2022-04-10 21:20:33,851 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    'authentication_form': self.login_form or AdminAuthenticationForm,
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:20:33,853 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 90088
ERROR 2022-04-10 21:20:35,581 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    'authentication_form': self.login_form or AdminAuthenticationForm,
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:20:35,582 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 90088
ERROR 2022-04-10 21:20:36,003 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    'authentication_form': self.login_form or AdminAuthenticationForm,
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:20:36,004 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 90088
ERROR 2022-04-10 21:20:36,201 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    'authentication_form': self.login_form or AdminAuthenticationForm,
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:20:36,203 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 90088
ERROR 2022-04-10 21:20:36,390 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    'authentication_form': self.login_form or AdminAuthenticationForm,
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:20:36,391 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 90088
ERROR 2022-04-10 21:20:36,614 log 228 50048 123145368592384 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 207, in inner
    return self.create_admin_view(self.login_view)(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py", line 66, in get
    'authentication_form': self.login_form or AdminAuthenticationForm,
TypeError: login() got an unexpected keyword argument 'extra_context'
ERROR 2022-04-10 21:20:36,616 basehttp 154 50048 123145368592384 "GET /xadmin/ HTTP/1.1" 500 90088
INFO 2022-04-10 21:23:26,626 autoreload 203 50048 140734748356032 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/website.py changed, reloading.
INFO 2022-04-10 21:23:29,045 autoreload 578 50898 140734983122368 Watching for file changes with StatReloader
INFO 2022-04-10 21:25:50,276 autoreload 578 51346 140734866574784 Watching for file changes with StatReloader
ERROR 2022-04-10 21:25:57,555 log 228 51346 123145577218048 Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/templatetags/xadmin_tags.py", line 40, in vendor
    return util_vendor(*tags).render()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py", line 102, in vendor
    media.add_css({'screen': files})
AttributeError: 'Media' object has no attribute 'add_css'
ERROR 2022-04-10 21:25:57,558 basehttp 154 51346 123145577218048 "GET /xadmin/ HTTP/1.1" 500 138942
INFO 2022-04-10 21:28:37,772 autoreload 203 51346 140734866574784 /Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/util.py changed, reloading.
INFO 2022-04-10 21:28:39,440 autoreload 578 51864 140734805720512 Watching for file changes with StatReloader
INFO 2022-04-10 21:29:18,360 autoreload 578 51996 140734898011584 Watching for file changes with StatReloader
INFO 2022-04-10 21:29:23,331 basehttp 154 51996 123145361350656 "GET /xadmin/ HTTP/1.1" 200 4151
INFO 2022-04-10 21:29:23,401 basehttp 154 51996 123145366605824 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 21:29:23,401 basehttp 154 51996 123145382371328 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 21:29:23,403 basehttp 154 51996 123145371860992 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 21:29:23,404 basehttp 154 51996 123145387626496 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 21:29:23,404 basehttp 154 51996 123145377116160 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 21:29:23,433 basehttp 154 51996 123145361350656 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 21:29:23,437 basehttp 154 51996 123145377116160 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 21:29:23,448 basehttp 154 51996 123145371860992 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 21:29:23,454 basehttp 154 51996 123145387626496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 21:29:23,468 basehttp 154 51996 123145366605824 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 21:29:23,470 basehttp 154 51996 123145382371328 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4158
INFO 2022-04-10 21:29:23,473 basehttp 154 51996 123145377116160 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 21:29:23,475 basehttp 154 51996 123145387626496 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 21:29:23,478 basehttp 154 51996 123145371860992 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2022-04-10 21:29:23,479 basehttp 154 51996 123145361350656 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-04-10 21:29:23,592 basehttp 154 51996 123145387626496 "GET /static/xadmin/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
INFO 2022-04-10 21:29:25,596 basehttp 154 51996 123145387626496 "POST /xadmin/ HTTP/1.1" 200 4388
INFO 2022-04-10 21:29:25,646 basehttp 154 51996 123145387626496 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4158
INFO 2022-04-10 21:30:22,834 autoreload 578 52301 140734833741248 Watching for file changes with StatReloader
INFO 2022-04-10 21:30:29,478 basehttp 154 52301 123145578381312 "POST /xadmin/ HTTP/1.1" 302 0
INFO 2022-04-10 21:30:29,616 basehttp 154 52301 123145578381312 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 21:30:29,675 basehttp 154 52301 123145578381312 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 21:30:29,685 basehttp 154 52301 123145594146816 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2022-04-10 21:30:29,689 basehttp 154 52301 123145588891648 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
ERROR 2022-04-10 21:30:29,848 log 228 52301 123145583636480 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 21:30:29,850 basehttp 154 52301 123145583636480 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:04:55,330 autoreload 203 52301 140734833741248 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/user/models.py changed, reloading.
INFO 2022-04-10 22:04:58,953 autoreload 578 58548 140734799453632 Watching for file changes with StatReloader
INFO 2022-04-10 22:07:07,505 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:07,658 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:07,662 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:07:09,022 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:09,120 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:09,121 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:07:09,754 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:09,839 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:09,840 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:07:10,183 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:10,266 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:10,268 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:07:10,443 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:10,536 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:10,537 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:07:11,549 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:11,638 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:11,639 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:07:13,339 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:13,419 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:13,420 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
ERROR 2022-04-10 22:07:15,415 log 228 58548 123145560014848 Internal Server Error: /xadmin/auth/user/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'CharField' object has no attribute 'rel'
ERROR 2022-04-10 22:07:15,418 basehttp 154 58548 123145560014848 "GET /xadmin/auth/user/ HTTP/1.1" 500 157081
INFO 2022-04-10 22:07:18,497 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:18,600 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:18,601 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
ERROR 2022-04-10 22:07:20,155 log 228 58548 123145560014848 Internal Server Error: /xadmin/xadmin/log/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'DateTimeField' object has no attribute 'rel'
ERROR 2022-04-10 22:07:20,158 basehttp 154 58548 123145560014848 "GET /xadmin/xadmin/log/ HTTP/1.1" 500 157141
INFO 2022-04-10 22:07:21,997 basehttp 154 58548 123145560014848 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:07:22,128 log 228 58548 123145560014848 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:07:22,130 basehttp 154 58548 123145560014848 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:08:50,907 autoreload 203 58548 140734799453632 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/user/models.py changed, reloading.
INFO 2022-04-10 22:08:54,421 autoreload 578 59279 140734840147392 Watching for file changes with StatReloader
INFO 2022-04-10 22:10:14,804 basehttp 154 59279 123145497059328 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:14,948 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:14,949 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:15,958 basehttp 154 59279 123145497059328 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:16,039 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:16,040 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:16,435 basehttp 154 59279 123145497059328 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:16,519 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:16,521 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:16,627 basehttp 154 59279 123145497059328 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:16,707 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:16,708 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:16,818 basehttp 154 59279 123145497059328 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:16,907 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:16,909 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:17,758 basehttp 154 59279 123145497059328 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 22:10:17,819 basehttp 154 59279 123145502314496 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 22:10:17,820 basehttp 154 59279 123145507569664 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 22:10:17,820 basehttp 154 59279 123145523335168 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 22:10:17,821 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 22:10:17,825 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 22:10:17,834 basehttp 154 59279 123145518080000 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 22:10:17,845 basehttp 154 59279 123145502314496 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 22:10:17,854 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 22:10:17,854 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 22:10:17,866 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 22:10:17,898 basehttp 154 59279 123145497059328 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2022-04-10 22:10:17,900 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 22:10:17,901 basehttp 154 59279 123145518080000 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 22:10:17,902 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-04-10 22:10:17,907 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 22:10:17,909 basehttp 154 59279 123145497059328 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
INFO 2022-04-10 22:10:17,916 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
ERROR 2022-04-10 22:10:17,963 log 228 59279 123145507569664 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:17,966 basehttp 154 59279 123145507569664 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76584
INFO 2022-04-10 22:10:18,021 basehttp 154 59279 123145502314496 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 22:10:18,086 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 22:10:18,086 basehttp 154 59279 123145523335168 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 22:10:18,089 basehttp 154 59279 123145518080000 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 22:10:18,090 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 22:10:18,104 basehttp 154 59279 123145523335168 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 22:10:18,110 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 22:10:18,137 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 22:10:18,148 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 22:10:18,174 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 22:10:18,174 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 22:10:18,199 basehttp 154 59279 123145507569664 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 22:10:18,206 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 22:10:18,207 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
ERROR 2022-04-10 22:10:18,233 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
INFO 2022-04-10 22:10:18,242 basehttp 154 59279 123145523335168 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 22:10:18,257 basehttp 154 59279 123145518080000 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
ERROR 2022-04-10 22:10:18,286 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76584
INFO 2022-04-10 22:10:18,300 basehttp 154 59279 123145507569664 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-04-10 22:10:18,304 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2022-04-10 22:10:18,321 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 22:10:18,370 basehttp 154 59279 123145507569664 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 22:10:18,418 basehttp 154 59279 123145502314496 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 22:10:18,435 basehttp 154 59279 123145518080000 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 22:10:18,436 basehttp 154 59279 123145523335168 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 22:10:18,438 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 22:10:18,438 basehttp 154 59279 123145502314496 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 22:10:18,440 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 22:10:18,454 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 22:10:18,482 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 22:10:18,483 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 22:10:18,486 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 22:10:18,506 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 22:10:18,519 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
ERROR 2022-04-10 22:10:18,558 log 228 59279 123145518080000 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
INFO 2022-04-10 22:10:18,562 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
ERROR 2022-04-10 22:10:18,569 basehttp 154 59279 123145518080000 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76584
INFO 2022-04-10 22:10:18,569 basehttp 154 59279 123145523335168 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
INFO 2022-04-10 22:10:18,569 basehttp 154 59279 123145497059328 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 22:10:18,604 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2022-04-10 22:10:18,609 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 22:10:18,609 basehttp 154 59279 123145507569664 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 22:10:18,671 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 22:10:18,687 basehttp 154 59279 123145518080000 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 22:10:18,689 basehttp 154 59279 123145523335168 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 22:10:18,696 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 22:10:18,699 basehttp 154 59279 123145497059328 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 22:10:18,713 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 22:10:18,715 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 22:10:18,723 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 22:10:18,728 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 22:10:18,739 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 22:10:18,741 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-04-10 22:10:18,744 basehttp 154 59279 123145507569664 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 22:10:18,747 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 22:10:18,816 basehttp 154 59279 123145512824832 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2022-04-10 22:10:18,818 basehttp 154 59279 123145507569664 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 22:10:18,820 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2022-04-10 22:10:18,820 basehttp 154 59279 123145497059328 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
ERROR 2022-04-10 22:10:18,877 log 228 59279 123145523335168 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
INFO 2022-04-10 22:10:18,916 basehttp 154 59279 123145518080000 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:18,955 basehttp 154 59279 123145523335168 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76584
INFO 2022-04-10 22:10:18,983 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 22:10:18,985 basehttp 154 59279 123145507569664 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 22:10:18,986 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 22:10:18,988 basehttp 154 59279 123145502314496 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 22:10:18,989 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 22:10:18,994 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 22:10:19,008 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 22:10:19,009 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 22:10:19,011 basehttp 154 59279 123145507569664 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 22:10:19,015 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 22:10:19,045 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-04-10 22:10:19,052 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 22:10:19,066 basehttp 154 59279 123145523335168 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 22:10:19,077 basehttp 154 59279 123145518080000 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
INFO 2022-04-10 22:10:19,079 basehttp 154 59279 123145507569664 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2022-04-10 22:10:19,084 basehttp 154 59279 123145523335168 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 22:10:19,085 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
ERROR 2022-04-10 22:10:19,129 log 228 59279 123145497059328 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:19,138 basehttp 154 59279 123145497059328 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76584
INFO 2022-04-10 22:10:19,161 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
INFO 2022-04-10 22:10:19,234 basehttp 154 59279 123145518080000 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2022-04-10 22:10:19,240 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2022-04-10 22:10:19,244 basehttp 154 59279 123145502314496 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8324
INFO 2022-04-10 22:10:19,251 basehttp 154 59279 123145507569664 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2022-04-10 22:10:19,252 basehttp 154 59279 123145518080000 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2022-04-10 22:10:19,253 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2022-04-10 22:10:19,256 basehttp 154 59279 123145497059328 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2022-04-10 22:10:19,269 basehttp 154 59279 123145507569664 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2022-04-10 22:10:19,293 basehttp 154 59279 123145518080000 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2022-04-10 22:10:19,294 basehttp 154 59279 123145523335168 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2022-04-10 22:10:19,297 basehttp 154 59279 123145502314496 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2022-04-10 22:10:19,297 basehttp 154 59279 123145507569664 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2022-04-10 22:10:19,298 basehttp 154 59279 123145497059328 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2022-04-10 22:10:19,310 basehttp 154 59279 123145518080000 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2022-04-10 22:10:19,315 basehttp 154 59279 123145523335168 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2022-04-10 22:10:19,317 basehttp 154 59279 123145497059328 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2022-04-10 22:10:19,318 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
ERROR 2022-04-10 22:10:19,359 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:19,360 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76584
INFO 2022-04-10 22:10:19,394 basehttp 154 59279 123145512824832 "GET /static/xadmin/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
WARNING 2022-04-10 22:10:19,421 log 228 59279 123145512824832 Not Found: /favicon.ico
WARNING 2022-04-10 22:10:19,422 basehttp 154 59279 123145512824832 "GET /favicon.ico HTTP/1.1" 404 2309
ERROR 2022-04-10 22:10:22,852 log 228 59279 123145512824832 Internal Server Error: /xadmin/auth/user/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'CharField' object has no attribute 'rel'
ERROR 2022-04-10 22:10:22,856 basehttp 154 59279 123145512824832 "GET /xadmin/auth/user/ HTTP/1.1" 500 157081
INFO 2022-04-10 22:10:31,953 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:32,076 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:32,077 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:34,523 basehttp 154 59279 123145512824832 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
INFO 2022-04-10 22:10:34,562 basehttp 154 59279 123145512824832 "GET /static/xadmin/css/xadmin.form.css HTTP/1.1" 200 3763
INFO 2022-04-10 22:10:34,593 basehttp 154 59279 123145497059328 "GET /static/xadmin/js/xadmin.plugin.filters.js HTTP/1.1" 200 1990
INFO 2022-04-10 22:10:34,594 basehttp 154 59279 123145502314496 "GET /static/xadmin/js/xadmin.plugin.bookmark.js HTTP/1.1" 200 529
INFO 2022-04-10 22:10:34,595 basehttp 154 59279 123145523335168 "GET /static/xadmin/js/xadmin.plugin.details.js HTTP/1.1" 200 2319
INFO 2022-04-10 22:10:34,595 basehttp 154 59279 123145518080000 "GET /static/xadmin/js/xadmin.page.list.js HTTP/1.1" 200 1105
INFO 2022-04-10 22:10:34,598 basehttp 154 59279 123145507569664 "GET /static/xadmin/js/xadmin.page.form.js HTTP/1.1" 200 1948
ERROR 2022-04-10 22:10:34,654 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:34,655 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
ERROR 2022-04-10 22:10:38,890 log 228 59279 123145512824832 Internal Server Error: /xadmin/reversion/revision/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'DateTimeField' object has no attribute 'rel'
ERROR 2022-04-10 22:10:38,894 basehttp 154 59279 123145512824832 "GET /xadmin/reversion/revision/ HTTP/1.1" 500 157570
INFO 2022-04-10 22:10:40,538 basehttp 154 59279 123145512824832 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:10:40,657 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:40,658 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:10:45,430 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:10:45,526 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:10:45,527 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:10:50,156 basehttp 154 59279 123145512824832 "GET /xadmin/logout/ HTTP/1.1" 200 2651
INFO 2022-04-10 22:10:50,207 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4158
INFO 2022-04-10 22:10:52,535 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 4151
INFO 2022-04-10 22:10:52,584 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4158
INFO 2022-04-10 22:10:54,939 basehttp 154 59279 123145512824832 "POST /xadmin/ HTTP/1.1" 200 4388
INFO 2022-04-10 22:10:54,997 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4158
INFO 2022-04-10 22:11:00,438 basehttp 154 59279 123145512824832 "POST /xadmin/ HTTP/1.1" 302 0
INFO 2022-04-10 22:11:00,479 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:11:00,560 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:00,561 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:11:04,737 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:11:04,813 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:04,814 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
ERROR 2022-04-10 22:11:06,046 log 228 59279 123145512824832 Internal Server Error: /xadmin/reversion/revision/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'DateTimeField' object has no attribute 'rel'
ERROR 2022-04-10 22:11:06,050 basehttp 154 59279 123145512824832 "GET /xadmin/reversion/revision/ HTTP/1.1" 500 157559
INFO 2022-04-10 22:11:07,742 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:11:07,854 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:07,856 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
ERROR 2022-04-10 22:11:09,180 log 228 59279 123145512824832 Internal Server Error: /xadmin/xadmin/log/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'DateTimeField' object has no attribute 'rel'
ERROR 2022-04-10 22:11:09,184 basehttp 154 59279 123145512824832 "GET /xadmin/xadmin/log/ HTTP/1.1" 500 157141
INFO 2022-04-10 22:11:11,624 basehttp 154 59279 123145512824832 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:11:11,701 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:11,702 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:11:13,295 basehttp 154 59279 123145512824832 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:13,391 log 228 59279 123145512824832 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:13,392 basehttp 154 59279 123145512824832 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:23,681 autoreload 203 59279 140734840147392 /Users/zhangjiangying/study/luffyapi/luffyapi/apps/user/models.py changed, reloading.
INFO 2022-04-10 22:11:27,170 autoreload 578 59767 140734779551168 Watching for file changes with StatReloader
INFO 2022-04-10 22:11:28,044 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:28,326 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:28,327 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:31,006 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:31,097 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:31,098 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:31,749 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:31,838 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:31,839 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:31,991 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:32,091 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:32,093 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:32,384 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:32,480 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:32,481 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:33,191 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:33,294 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:33,295 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:33,669 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:33,755 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:33,757 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
INFO 2022-04-10 22:11:33,917 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
ERROR 2022-04-10 22:11:34,011 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:11:34,014 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76334
ERROR 2022-04-10 22:11:35,174 log 228 59767 123145351737344 Internal Server Error: /xadmin/auth/user/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'CharField' object has no attribute 'rel'
ERROR 2022-04-10 22:11:35,177 basehttp 154 59767 123145351737344 "GET /xadmin/auth/user/ HTTP/1.1" 500 157092
INFO 2022-04-10 22:11:38,256 basehttp 154 59767 123145351737344 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
INFO 2022-04-10 22:13:47,965 basehttp 154 59767 123145351737344 "GET /xadmin/auth/user/add/ HTTP/1.1" 200 12937
ERROR 2022-04-10 22:13:48,179 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:13:48,181 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76337
INFO 2022-04-10 22:13:58,800 basehttp 154 59767 123145351737344 "POST /xadmin/auth/user/add/ HTTP/1.1" 200 13523
ERROR 2022-04-10 22:13:58,935 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:13:58,937 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76337
INFO 2022-04-10 22:14:18,822 basehttp 154 59767 123145351737344 "POST /xadmin/auth/user/add/ HTTP/1.1" 200 13364
ERROR 2022-04-10 22:14:18,985 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:14:18,987 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76337
INFO 2022-04-10 22:14:34,482 basehttp 154 59767 123145351737344 "POST /xadmin/auth/user/add/ HTTP/1.1" 302 0
ERROR 2022-04-10 22:14:34,639 log 228 59767 123145351737344 Internal Server Error: /xadmin/auth/user/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 404, in get
    response = self.get_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 203, in get_result_list
    return self.make_result_list()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 175, in make_result_list
    self.list_queryset = self.get_list_queryset()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 81, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 64, in filter_chain
    return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 50, in filter_chain
    return func()
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 63, in _inner_method
    return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/base.py", line 75, in _inner_method
    return func(self, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/views/list.py", line 231, in get_list_queryset
    if isinstance(field.rel, models.ManyToOneRel):
AttributeError: 'CharField' object has no attribute 'rel'
ERROR 2022-04-10 22:14:34,642 basehttp 154 59767 123145351737344 "GET /xadmin/auth/user/ HTTP/1.1" 500 158024
INFO 2022-04-10 22:14:42,722 basehttp 154 59767 123145351737344 "GET /xadmin/auth/user/add/ HTTP/1.1" 200 13223
ERROR 2022-04-10 22:14:43,093 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:14:43,125 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76337
INFO 2022-04-10 22:14:43,200 basehttp 154 59767 123145356992512 "GET /xadmin/auth/group/ HTTP/1.1" 200 19040
INFO 2022-04-10 22:14:43,366 basehttp 154 59767 123145351737344 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:14:43,610 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:14:43,645 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:14:45,342 basehttp 154 59767 123145351737344 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:14:45,630 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:14:45,631 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
INFO 2022-04-10 22:14:47,498 basehttp 154 59767 123145351737344 "GET /xadmin/ HTTP/1.1" 200 9819
ERROR 2022-04-10 22:14:47,624 log 228 59767 123145351737344 Internal Server Error: /xadmin/jsi18n/
Traceback (most recent call last):
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/xadmin/sites.py", line 349, in i18n_javascript
    from django.views.i18n import javascript_catalog
ImportError: cannot import name 'javascript_catalog' from 'django.views.i18n' (/Users/zhangjiangying/study/luffyapi/venv/lib/python3.7/site-packages/django/views/i18n.py)
ERROR 2022-04-10 22:14:47,642 basehttp 154 59767 123145351737344 "GET /xadmin/jsi18n/ HTTP/1.1" 500 76323
